// NcodeCenter DB 스키마 (docs/NcodeCenter-DB.md 기준) — 앱 스키마 뷰용 데이터
export type Column = { name: string; type: string; key?: "PK" | "FK"; note?: string };
export type Table = { name: string; label: string; group: string; columns: Column[]; note?: string };
export type Relation = { from: string; to: string; note?: string };

export const GROUPS = ["참조", "업체·정책", "원장(Owner·Book)", "프로젝트·편집", "워크플로우", "운영"] as const;

export const TABLES: Table[] = [
  {
    name: "sections_dim", label: "Section 참조표", group: "참조",
    note: "N코드 정보표(제품×Section별 max·length)",
    columns: [
      { name: "product", type: "text", key: "PK", note: "PDS2=Gcode / PDS3=Ncode" },
      { name: "section", type: "int", key: "PK" },
      { name: "owner_max", type: "bigint" },
      { name: "book_max", type: "int" },
      { name: "page_max", type: "int" },
      { name: "length_mm", type: "int" },
    ],
  },
  {
    name: "grades", label: "등급 정책", group: "업체·정책",
    columns: [
      { name: "id", type: "serial", key: "PK" },
      { name: "name", type: "text", note: "A/B/C" },
      { name: "auto_page_cap", type: "bigint", note: "자동 할당 상한" },
      { name: "volume_approval_pages", type: "int", note: "초과 시 승인 전환" },
    ],
  },
  {
    name: "grade_so", label: "등급별 SO (정책 §3)", group: "업체·정책",
    note: "등급×코드종류 → Section·페이지상한 (a=S0/1000p, b=S3/100p)",
    columns: [
      { name: "id", type: "serial", key: "PK" },
      { name: "grade_id", type: "int", key: "FK", note: "→ grades" },
      { name: "code_type", type: "text", note: "N / G" },
      { name: "section", type: "int", note: "등급별 S" },
      { name: "page_cap", type: "int" },
    ],
  },
  {
    name: "customers", label: "고객사 (ACCOUNT)", group: "업체·정책",
    note: "고객사 마스터. 계층(상위/하위/단독)은 공통코드 보유(common_codes)·사용 멤버십(common_members)으로 판정. 서비스·등급은 코드 할당/프로젝트에서 지정.",
    columns: [
      { name: "id", type: "serial", key: "PK" },
      { name: "name", type: "text", note: "업체명" },
      { name: "manager / contact", type: "text", note: "담당자 / 연락처" },
      { name: "address / biz_no", type: "text", note: "주소 / 사업자등록번호" },
      { name: "bank_name / account_no", type: "text", note: "은행 / 계좌" },
      { name: "tax_email", type: "text", note: "세금계산서 이메일" },
      { name: "rates", type: "jsonb", note: "편집 단가(2026 항목별) — key(s_page/s_edit/s_cmp2…/w_none…)→단가, 미지정=전사 기본값" },
      { name: "page_unit / symbol_unit", type: "int", note: "(구) 적용/편집 단가 — rates로 흡수" },
      { name: "docs", type: "jsonb", note: "관련 서류(라벨+파일명)" },
      { name: "closed / closed_note", type: "bool / text", note: "프로젝트 종료 = 발급 이력만 유지" },
    ],
  },
  {
    name: "customer_users", label: "고객 사용자 (서비스 계정)", group: "업체·정책",
    columns: [
      { name: "id", type: "serial", key: "PK" },
      { name: "customer_id", type: "int", key: "FK", note: "→ customers" },
      { name: "user_ref", type: "text", note: "계정 ID(email) · App Key 연동" },
      { name: "services", type: "text[]", note: "사용처(중복 선택) — CASTERN / FORMSOLUTION / SDK. 선택한 서비스에서만 로그인 허용" },
      { name: "service_settings", type: "jsonb", note: "서비스별 권한·설정 — 현재 CasterN 권한 6종만 정의(그 외 준비중)" },
    ],
  },
  {
    name: "common_codes", label: "공통(커먼)코드 레지스트리", group: "업체·정책",
    note: "코드 정본 = (타입 k, Section, Owner). 대장(holder) 회사가 보유 = 상위 고객사. PC-006~009.",
    columns: [
      { name: "code_type (k)", type: "text", key: "PK", note: "N(PDS3) / G(PDS2) / A(IDS·이력전용)" },
      { name: "section / owner", type: "int / bigint", key: "PK" },
      { name: "name / holder", type: "text", note: "코드명 / 대표 브랜드(그룹)" },
      { name: "company", type: "text", note: "보유 대장 고객사(= 상위)" },
      { name: "history_only", type: "bool", note: "A(IDS) = 코드 할당·편집 없이 검색/이력만" },
    ],
  },
  {
    name: "common_members", label: "공통코드 사용 멤버십 (하위)", group: "업체·정책",
    note: "공통코드를 사용하는 하위 고객사. (k,Section,Owner) → 고객사. 빌드 시드 + 수동 추가. PC-013·014.",
    columns: [
      { name: "id", type: "serial", key: "PK" },
      { name: "code_type / section / owner", type: "", key: "FK", note: "→ common_codes" },
      { name: "customer_id", type: "int", key: "FK", note: "→ customers (하위 고객사)" },
      { name: "seeded", type: "bool", note: "빌드 시드 / 수동 추가 구분" },
    ],
  },
  {
    name: "owner_pins", label: "전용 owner 고정", group: "업체·정책",
    note: "자동 대상(폼솔루션) 전용 owner",
    columns: [
      { name: "id", type: "serial", key: "PK" },
      { name: "customer_id", type: "int", key: "FK", note: "→ customers" },
      { name: "product", type: "text" },
      { name: "section", type: "int" },
      { name: "owner", type: "bigint" },
    ],
  },
  {
    name: "reservations", label: "사전 예약 (레거시·미사용)", group: "업체·정책",
    note: "예약 개념 폐기(PC-004) — 스키마만 남긴 레거시 테이블. 신규 로직에서 사용하지 않음.",
    columns: [
      { name: "id", type: "serial", key: "PK" },
      { name: "customer_id", type: "int", key: "FK", note: "→ customers" },
      { name: "product / section / owner", type: "" },
      { name: "book_start / book_end", type: "int" },
      { name: "page_start / page_end", type: "int" },
    ],
  },
  {
    name: "allocations", label: "할당 원장 (Owner×Book)", group: "원장(Owner·Book)",
    note: "한 행 = Owner 아래 하나의 Book. 소유권·대시보드 근간.",
    columns: [
      { name: "id", type: "bigserial", key: "PK" },
      { name: "customer_id", type: "int", key: "FK", note: "업체 → customers" },
      { name: "product", type: "text", note: "PDS2/3(≈G/N)" },
      { name: "code_type", type: "text", note: "코드 종류 N/G (S 제외)" },
      { name: "pen_type", type: "text", note: "Ncp(소리펜)/Ndp(필기펜) 분리" },
      { name: "section", type: "int" },
      { name: "owner", type: "bigint", note: "Owner = 프로젝트" },
      { name: "project_name", type: "text", note: "프로젝트명" },
      { name: "book_start / book_end", type: "int", note: "Book = 상품" },
      { name: "page_start / page_end", type: "int", note: "Page" },
      { name: "book_name", type: "text", note: "상품/교재명" },
      { name: "usage_status", type: "text", note: "코드 상태 — 모두 '할당됨'(예약/사용중 구분 폐기, PC-004)" },
      { name: "source", type: "text", note: "AUTO/MANUAL/IMPORT" },
      { name: "is_deleted", type: "bool" },
      { name: "issued_at", type: "timestamptz" },
    ],
  },
  {
    name: "projects", label: "코드 프로젝트 (조회 전용)", group: "프로젝트·편집",
    note: "업체별 프로젝트(발급 SOBP+사용 서비스). 화면은 조회·검색 전용(등록 없음, PC-011). editing_owner로 편집과 연결.",
    columns: [
      { name: "id", type: "serial", key: "PK" },
      { name: "customer_id", type: "int", key: "FK", note: "→ customers(고객사)" },
      { name: "name", type: "text", note: "프로젝트명" },
      { name: "service", type: "text", note: "CASTERN / FORMSOLUTION / NONE(코드만 발급) — SOBP 할당에서 지정" },
      { name: "grade", type: "text", note: "폼솔루션 등급(a/b/c)" },
      { name: "editing_owner", type: "bigint", note: "★ 편집(editing_books.owner) 연결" },
      { name: "symbols", type: "int", note: "편집 심볼 총합(진행 표시)" },
      { name: "editing / shared / code_only", type: "bool", note: "편집등록(=casterN) / 공유(커먼) / 코드발급-only" },
    ],
  },
  {
    name: "project_issued", label: "발급 SOBP 내역", group: "프로젝트·편집",
    note: "프로젝트가 발급받은 코드 블록. codes = 페이지 용량(페이지 수).",
    columns: [
      { name: "id", type: "serial", key: "PK" },
      { name: "project_id", type: "int", key: "FK", note: "→ projects" },
      { name: "section / owner", type: "int / bigint" },
      { name: "book_start / book_end", type: "int" },
      { name: "page_start / page_end", type: "int" },
      { name: "codes", type: "int", note: "발급 코드 수 = 페이지 용량" },
      { name: "issued_at", type: "date" },
    ],
  },
  {
    name: "editing_books", label: "편집 프로젝트 (책 단위)", group: "프로젝트·편집",
    note: "엑셀(2_New_NSP) 38컬럼 원장. 소리펜7·필기펜4 모드별 심볼 → 편집 비용.",
    columns: [
      { name: "id", type: "bigserial", key: "PK" },
      { name: "customer_id", type: "int", key: "FK", note: "→ customers (고객사)" },
      { name: "owner", type: "bigint", note: "★ projects.editing_owner와 매칭" },
      { name: "section / book", type: "int" },
      { name: "code_type", type: "text", note: "코드 구분 N / G" },
      { name: "pen_type / pen_model", type: "text", note: "타입(소리펜/필기펜) / 펜모델(C90…)" },
      { name: "title / ncp2_file", type: "text", note: "교재명 / ncp2 파일명" },
      { name: "start_page / total_page", type: "int", note: "Start Page / Total Page" },
      { name: "resource_mb", type: "numeric", note: "ncp2 파일 크기(디바이스 저장)" },
      { name: "issued_at / deleted_at", type: "date", note: "북코드 발급/삭제일자" },
      { name: "ncp2_modified_at", type: "date", note: "ncp2 최종 수정 날짜" },
      { name: "issuer", type: "text", note: "발급인" },
      { name: "sound_symbols", type: "jsonb", note: "소리펜 항목별 수량(15): Ncode적용·편집기본·Compound2~8언어·슬롯전환·그룹재생·게임·프롬프트·RAG·4도출력 `PC-085`" },
      { name: "pen_symbols", type: "jsonb", note: "필기펜 항목별 수량(4): Ncode적용·기본편집·Custom·노트서버업로드 `PC-084` `PC-085`" },
      { name: "symbol_total", type: "int", note: "소리펜합 + 필기펜합" },
      { name: "edit_methods", type: "text[]", note: "편집방식 복수" },
      { name: "kep_used / set_count", type: "text / int", note: "교원구몬 사용여부(O/X) / 세트 개수" },
      { name: "detail / output_file / app_data", type: "jsonb", note: "세부내역·출력용파일·APP데이터 (첨부: 링크/파일+설명)" },
      { name: "work_logs", type: "jsonb", note: "업무요청 메모(요청/처리/메모) — 메모1~3 대체" },
    ],
  },
  {
    name: "work_logs", label: "업무 원장 (메모)", group: "프로젝트·편집",
    note: "고객사+프로젝트 단일 원장. no = 고객사 내 안정 번호(삭제해도 유지).",
    columns: [
      { name: "id", type: "bigserial", key: "PK" },
      { name: "no", type: "int", note: "고객사 내 표시번호" },
      { name: "customer_id", type: "int", key: "FK", note: "→ customers" },
      { name: "project_id", type: "int", key: "FK", note: "→ projects (NULL=고객사 공통)" },
      { name: "kind", type: "text", note: "요청/처리/메모" },
      { name: "content / author", type: "text" },
      { name: "log_date", type: "date" },
    ],
  },
  {
    name: "tickets", label: "티켓 (기간·페이지 limit)", group: "워크플로우",
    columns: [
      { name: "id", type: "bigserial", key: "PK" },
      { name: "allocation_id", type: "bigint", key: "FK", note: "→ allocations" },
      { name: "customer_id", type: "int", key: "FK", note: "→ customers" },
      { name: "section / owner / book / page", type: "" },
      { name: "book_allowed_max / page_allowed_max", type: "int" },
      { name: "issue_time / expire_time", type: "timestamptz", note: "expire NULL=무제한" },
      { name: "status", type: "text", note: "ISSUED/EXPIRED/REVOKED" },
    ],
  },
  {
    name: "allocation_requests", label: "코드 요청/승인", group: "워크플로우",
    columns: [
      { name: "id", type: "bigserial", key: "PK" },
      { name: "customer_id", type: "int", key: "FK", note: "→ customers" },
      { name: "product / requested_pages", type: "" },
      { name: "mode", type: "text", note: "AUTO / APPROVAL" },
      { name: "status", type: "text", note: "PENDING→APPROVED/REJECTED→ISSUED" },
      { name: "result_allocation_id", type: "bigint", key: "FK", note: "→ allocations" },
    ],
  },
  {
    name: "staff_users", label: "내부 직원", group: "운영",
    columns: [
      { name: "id", type: "text", key: "PK", note: "이메일" },
      { name: "name", type: "text" },
      { name: "role", type: "text", note: "ADMIN / STAFF" },
      { name: "enabled", type: "bool" },
    ],
  },
  {
    name: "activity_log", label: "활동 로그 (직원 audit)", group: "운영",
    columns: [
      { name: "id", type: "bigserial", key: "PK" },
      { name: "actor_id", type: "text", key: "FK", note: "→ staff_users" },
      { name: "action", type: "text", note: "APPROVE/ISSUE/DELETE…" },
      { name: "target_type / target_id", type: "" },
      { name: "detail", type: "jsonb" },
    ],
  },
];

export const RELATIONS: Relation[] = [
  { from: "grade_so", to: "grades" },
  { from: "common_codes", to: "customers", note: "company = 대장(상위)" },
  { from: "common_members", to: "common_codes", note: "k/section/owner" },
  { from: "common_members", to: "customers", note: "하위 고객사" },
  { from: "customer_users", to: "customers" },
  { from: "owner_pins", to: "customers" },
  { from: "reservations", to: "customers" },
  { from: "allocations", to: "customers" },
  { from: "projects", to: "customers" },
  { from: "project_issued", to: "projects" },
  { from: "editing_books", to: "customers", note: "owner ↔ projects.editing_owner" },
  { from: "work_logs", to: "customers" },
  { from: "work_logs", to: "projects", note: "project_id (nullable)" },
  { from: "tickets", to: "allocations" },
  { from: "tickets", to: "customers" },
  { from: "allocation_requests", to: "customers" },
  { from: "allocation_requests", to: "allocations", note: "result" },
  { from: "activity_log", to: "staff_users" },
];
